DELETE FROM `mdl_sr_management_tiles`;
INSERT INTO `mdl_sr_management_tiles` (`id`, `title`, `button_name`, `button_url`, `button_icon`, `list_element_1`, `list_element_2`, `list_element_3`, `list_element_4`, `color`, `tile_order`, `plugin`, `user_id`, `task_path`, `function`, `moodle_capability`, `element_1_link`, `element_2_link`, `element_3_link`, `element_4_link`) VALUES
(1, 'Student Registration', 'Manage', '/local/student_registration/views/Menu.php', 'fa fa-user', '#1', '#2', '#3', '#4', 'danger', 1, 'Management Dashboard', 2, 'dashboard_lib.php', 'get_tasks_md', 'local/management_dashbaord:view', '/local/student_registration/views/ST_process/ST_prcess_overview.php', NULL, NULL, NULL),
(4, 'Student Registration', 'Manage', '/local/student_registration/views/ST_process/ST_prcess_overview.php', 'fa fa-user', '#5', '', '', '', 'danger', 1, 'Student Registration', 2, '../dashboard_lib.php', 'get_tasks_md', 'local/student_registration:manage', NULL, NULL, NULL, NULL),
(5, 'Capacity Planning', 'Manage', '/local/student_registration/views/ST_process/ST_active_process_Ma_CP.php', 'fa fa-user', '', '', '', '', 'danger', 2, 'Student Registration', 2, '', NULL, 'local/student_registration:manage', NULL, NULL, NULL, NULL),
(6, 'Course Management', 'Manage', '/local/student_registration/views/ST_process/ST_active_process_Ma_CC.php', 'fa fa-user', '', '', '', '', 'danger', 3, 'Student Registration', 2, '', NULL, 'local/student_registration:manage', NULL, NULL, NULL, NULL),
(7, 'Settings for STRE', 'Edit', '/local/student_registration/views/Settings.php', 'fa fa-globe', '', '', '', '', 'danger', 6, 'Student Registration', 2, '', '', 'local/student_registration:manage', '', '', '', ''),
(8, 'Lecturer recruitment', 'Manage', '/local/lecrec/index.php', 'fa fa-user', 'Help center access', '', '', '', 'danger', 3, 'Management Dashboard', 2, '', '', 'local/management_dashbaord:view', NULL, NULL, NULL, NULL),
(10, 'Study Programs Management', 'Manage', '/local/student_registration/views/SP_master_data/SP_Master_Data.php', 'fa fa-user', 'Add new Study Programs', 'Adjust existing Study Programs', '', '', 'danger', 4, 'Student Registration', 2, '', '', 'local/student_registration:manage', '', '', '', ''),
(11, 'Student Registration', 'Manage', '/local/student_registration/views/ST_process/ST_active_process_CR_ST.php', 'fa fa-user', 'Register Students', '', '', '', 'danger', 2, 'Student Registration', 2, '', NULL, 'local/student_registration:cr', NULL, NULL, NULL, NULL),
(13, 'Demand Planning', 'Manage', '/local/student_registration/views/ST_process/ST_active_process_CR_DP.php', 'fa fa-user', 'Submit your Demand Planning', NULL, NULL, NULL, 'danger', 1, 'Student Registration', 2, NULL, NULL, 'local/student_registration:cr', NULL, NULL, NULL, NULL),
(14, 'Reporting', 'View', '/local/student_registration/views/ST_Reporting/ST_reporting_main.php', 'fa fa-bar-chart', '', '', '', '', 'danger', 5, 'Student Registration', 2, '', '', 'local/student_registration:manage', '', '', '', ''),
(16, 'Partner Company Management', 'Manage', '/local/student_registration/views/DG_master_data/DG_company.php', 'fa fa-bar-user', '', '', '', '', 'danger', 2, 'Management Dashboard', 2, '', '', 'local/management_dashbaord:view', '', '', '', '');
